// AlpacaHTTP
// Copyright (c) 2025-2026 Joey Troy and contributors
//
// This file is part of AlpacaHTTP.
//
// AlpacaHTTP is licensed under the GNU Affero General Public License,
// version 3 or (at your option) any later version (AGPL-3.0-or-later),
// with an additional permission allowing combination with proprietary
// device-vendor SDKs. See the LICENSE file in this repository for the full
// license text and the vendor-SDK linking exception, or the license online at:
// https://www.gnu.org/licenses/agpl-3.0.html

#pragma once

// Committed snapshot of every (device type, method, verb mask) the router
// accepts (#646), captured from the k*Methods tables in
// AlpacaHTTP/src/http/router.cpp at origin/main c4640d6e. Not the ASCOM spec:
// it includes this repo's extensions (filterwheel PUT names/focusoffsets,
// rotator PUT targetposition, switch cancelasync, dome canslew,
// observingconditions seeing). test_route_table.cpp compares the live router
// against this list in both directions, so ANY change to the accepted surface
// shows up as a row diff here. Update it deliberately, in the same commit as
// the router change.
//
// The "common" pseudo-type is kCommonMethods, accepted by every device type.
// Rows are sorted by method name within each type block.

#include <cstddef>

namespace route_table_fixture {

constexpr unsigned kGet = 1;
constexpr unsigned kPut = 2;

struct RouteRow {
    const char* type;
    const char* method;
    unsigned mask;
};

constexpr RouteRow kRoutes[] = {
    // ---- common ----
    {"common", "action", kPut},
    {"common", "commandblind", kPut},
    {"common", "commandbool", kPut},
    {"common", "commandstring", kPut},
    {"common", "connect", kPut},
    {"common", "connected", kGet | kPut},
    {"common", "connecting", kGet},
    {"common", "description", kGet},
    {"common", "devicestate", kGet},
    {"common", "disconnect", kPut},
    {"common", "driverinfo", kGet},
    {"common", "driverversion", kGet},
    {"common", "interfaceversion", kGet},
    {"common", "name", kGet},
    {"common", "supportedactions", kGet},
    // ---- camera ----
    {"camera", "abortexposure", kPut},
    {"camera", "bayeroffsetx", kGet},
    {"camera", "bayeroffsety", kGet},
    {"camera", "binx", kGet | kPut},
    {"camera", "biny", kGet | kPut},
    {"camera", "camerastate", kGet},
    {"camera", "cameraxsize", kGet},
    {"camera", "cameraysize", kGet},
    {"camera", "canabortexposure", kGet},
    {"camera", "canasymmetricbin", kGet},
    {"camera", "canfastreadout", kGet},
    {"camera", "cangetcoolerpower", kGet},
    {"camera", "canpulseguide", kGet},
    {"camera", "cansetccdtemperature", kGet},
    {"camera", "canstopexposure", kGet},
    {"camera", "ccdtemperature", kGet},
    {"camera", "cooleron", kGet | kPut},
    {"camera", "coolerpower", kGet},
    {"camera", "electronsperadu", kGet},
    {"camera", "exposuremax", kGet},
    {"camera", "exposuremin", kGet},
    {"camera", "exposureresolution", kGet},
    {"camera", "fastreadout", kGet | kPut},
    {"camera", "fullwellcapacity", kGet},
    {"camera", "gain", kGet | kPut},
    {"camera", "gainmax", kGet},
    {"camera", "gainmin", kGet},
    {"camera", "gains", kGet},
    {"camera", "hasshutter", kGet},
    {"camera", "heatsinktemperature", kGet},
    {"camera", "imagearray", kGet},
    {"camera", "imagearrayvariant", kGet},
    {"camera", "imageready", kGet},
    {"camera", "ispulseguiding", kGet},
    {"camera", "lastexposureduration", kGet},
    {"camera", "lastexposurestarttime", kGet},
    {"camera", "maxadu", kGet},
    {"camera", "maxbinx", kGet},
    {"camera", "maxbiny", kGet},
    {"camera", "numx", kGet | kPut},
    {"camera", "numy", kGet | kPut},
    {"camera", "offset", kGet | kPut},
    {"camera", "offsetmax", kGet},
    {"camera", "offsetmin", kGet},
    {"camera", "offsets", kGet},
    {"camera", "percentcompleted", kGet},
    {"camera", "pixelsizex", kGet},
    {"camera", "pixelsizey", kGet},
    {"camera", "pulseguide", kPut},
    {"camera", "readoutmode", kGet | kPut},
    {"camera", "readoutmodes", kGet},
    {"camera", "sensorname", kGet},
    {"camera", "sensortype", kGet},
    {"camera", "setccdtemperature", kGet | kPut},
    {"camera", "startexposure", kPut},
    {"camera", "startx", kGet | kPut},
    {"camera", "starty", kGet | kPut},
    {"camera", "stopexposure", kPut},
    {"camera", "subexposureduration", kGet | kPut},
    // ---- telescope ----
    {"telescope", "abortslew", kPut},
    {"telescope", "alignmentmode", kGet},
    {"telescope", "altitude", kGet},
    {"telescope", "aperturearea", kGet},
    {"telescope", "aperturediameter", kGet},
    {"telescope", "athome", kGet},
    {"telescope", "atpark", kGet},
    {"telescope", "axisrates", kGet},
    {"telescope", "azimuth", kGet},
    {"telescope", "canfindhome", kGet},
    {"telescope", "canmoveaxis", kGet},
    {"telescope", "canpark", kGet},
    {"telescope", "canpulseguide", kGet},
    {"telescope", "cansetdeclinationrate", kGet},
    {"telescope", "cansetguiderates", kGet},
    {"telescope", "cansetpark", kGet},
    {"telescope", "cansetpierside", kGet},
    {"telescope", "cansetrightascensionrate", kGet},
    {"telescope", "cansettracking", kGet},
    {"telescope", "canslew", kGet},
    {"telescope", "canslewaltaz", kGet},
    {"telescope", "canslewaltazasync", kGet},
    {"telescope", "canslewasync", kGet},
    {"telescope", "cansync", kGet},
    {"telescope", "cansyncaltaz", kGet},
    {"telescope", "canunpark", kGet},
    {"telescope", "declination", kGet},
    {"telescope", "declinationrate", kGet | kPut},
    {"telescope", "destinationsideofpier", kGet},
    {"telescope", "doesrefraction", kGet | kPut},
    {"telescope", "equatorialsystem", kGet},
    {"telescope", "findhome", kPut},
    {"telescope", "focallength", kGet},
    {"telescope", "guideratedeclination", kGet | kPut},
    {"telescope", "guideraterightascension", kGet | kPut},
    {"telescope", "ispulseguiding", kGet},
    {"telescope", "moveaxis", kPut},
    {"telescope", "park", kPut},
    {"telescope", "pulseguide", kPut},
    {"telescope", "rightascension", kGet},
    {"telescope", "rightascensionrate", kGet | kPut},
    {"telescope", "setpark", kPut},
    {"telescope", "sideofpier", kGet | kPut},
    {"telescope", "siderealtime", kGet},
    {"telescope", "siteelevation", kGet | kPut},
    {"telescope", "sitelatitude", kGet | kPut},
    {"telescope", "sitelongitude", kGet | kPut},
    {"telescope", "slewing", kGet},
    {"telescope", "slewsettletime", kGet | kPut},
    {"telescope", "slewtoaltaz", kPut},
    {"telescope", "slewtoaltazasync", kPut},
    {"telescope", "slewtocoordinates", kPut},
    {"telescope", "slewtocoordinatesasync", kPut},
    {"telescope", "slewtotarget", kPut},
    {"telescope", "slewtotargetasync", kPut},
    {"telescope", "synctoaltaz", kPut},
    {"telescope", "synctocoordinates", kPut},
    {"telescope", "synctotarget", kPut},
    {"telescope", "targetdeclination", kGet | kPut},
    {"telescope", "targetrightascension", kGet | kPut},
    {"telescope", "tracking", kGet | kPut},
    {"telescope", "trackingrate", kGet | kPut},
    {"telescope", "trackingrates", kGet},
    {"telescope", "unpark", kPut},
    {"telescope", "utcdate", kGet | kPut},
    // ---- filterwheel ----
    {"filterwheel", "focusoffsets", kGet | kPut},
    {"filterwheel", "names", kGet | kPut},
    {"filterwheel", "position", kGet | kPut},
    // ---- focuser ----
    {"focuser", "absolute", kGet},
    {"focuser", "halt", kPut},
    {"focuser", "ismoving", kGet},
    {"focuser", "maxincrement", kGet},
    {"focuser", "maxstep", kGet},
    {"focuser", "move", kPut},
    {"focuser", "position", kGet},
    {"focuser", "stepsize", kGet},
    {"focuser", "tempcomp", kGet | kPut},
    {"focuser", "tempcompavailable", kGet},
    {"focuser", "temperature", kGet},
    // ---- rotator ----
    {"rotator", "canreverse", kGet},
    {"rotator", "halt", kPut},
    {"rotator", "ismoving", kGet},
    {"rotator", "mechanicalposition", kGet},
    {"rotator", "move", kPut},
    {"rotator", "moveabsolute", kPut},
    {"rotator", "movemechanical", kPut},
    {"rotator", "position", kGet},
    {"rotator", "reverse", kGet | kPut},
    {"rotator", "stepsize", kGet},
    {"rotator", "sync", kPut},
    {"rotator", "targetposition", kGet | kPut},
    // ---- dome ----
    {"dome", "abortslew", kPut},
    {"dome", "altitude", kGet},
    {"dome", "athome", kGet},
    {"dome", "atpark", kGet},
    {"dome", "azimuth", kGet},
    {"dome", "canfindhome", kGet},
    {"dome", "canpark", kGet},
    {"dome", "cansetaltitude", kGet},
    {"dome", "cansetazimuth", kGet},
    {"dome", "cansetpark", kGet},
    {"dome", "cansetshutter", kGet},
    {"dome", "canslave", kGet},
    {"dome", "canslew", kGet},
    {"dome", "cansyncazimuth", kGet},
    {"dome", "closeshutter", kPut},
    {"dome", "findhome", kPut},
    {"dome", "openshutter", kPut},
    {"dome", "park", kPut},
    {"dome", "setpark", kPut},
    {"dome", "shutterstatus", kGet},
    {"dome", "slaved", kGet | kPut},
    {"dome", "slewing", kGet},
    {"dome", "slewtoaltitude", kPut},
    {"dome", "slewtoazimuth", kPut},
    {"dome", "synctoazimuth", kPut},
    // ---- switch ----
    {"switch", "canasync", kGet},
    {"switch", "cancelasync", kGet | kPut},
    {"switch", "canwrite", kGet},
    {"switch", "getswitch", kGet},
    {"switch", "getswitchdescription", kGet},
    {"switch", "getswitchname", kGet},
    {"switch", "getswitchvalue", kGet},
    {"switch", "maxswitch", kGet},
    {"switch", "maxswitchvalue", kGet},
    {"switch", "minswitchvalue", kGet},
    {"switch", "setasync", kPut},
    {"switch", "setasyncvalue", kPut},
    {"switch", "setswitch", kPut},
    {"switch", "setswitchname", kPut},
    {"switch", "setswitchvalue", kPut},
    {"switch", "statechangecomplete", kGet},
    {"switch", "switchstep", kGet},
    // ---- covercalibrator ----
    {"covercalibrator", "brightness", kGet},
    {"covercalibrator", "calibratorchanging", kGet},
    {"covercalibrator", "calibratoroff", kPut},
    {"covercalibrator", "calibratoron", kPut},
    {"covercalibrator", "calibratorstate", kGet},
    {"covercalibrator", "closecover", kPut},
    {"covercalibrator", "covermoving", kGet},
    {"covercalibrator", "coverstate", kGet},
    {"covercalibrator", "haltcover", kPut},
    {"covercalibrator", "maxbrightness", kGet},
    {"covercalibrator", "opencover", kPut},
    // ---- observingconditions ----
    {"observingconditions", "averageperiod", kGet | kPut},
    {"observingconditions", "cloudcover", kGet},
    {"observingconditions", "dewpoint", kGet},
    {"observingconditions", "humidity", kGet},
    {"observingconditions", "pressure", kGet},
    {"observingconditions", "rainrate", kGet},
    {"observingconditions", "refresh", kPut},
    {"observingconditions", "seeing", kGet},
    {"observingconditions", "sensordescription", kGet},
    {"observingconditions", "skybrightness", kGet},
    {"observingconditions", "skyquality", kGet},
    {"observingconditions", "skytemperature", kGet},
    {"observingconditions", "starfwhm", kGet},
    {"observingconditions", "temperature", kGet},
    {"observingconditions", "timesincelastupdate", kGet},
    {"observingconditions", "winddirection", kGet},
    {"observingconditions", "windgust", kGet},
    {"observingconditions", "windspeed", kGet},
    // ---- safetymonitor ----
    {"safetymonitor", "issafe", kGet},
};

constexpr std::size_t kRouteCount = sizeof(kRoutes) / sizeof(kRoutes[0]);

}  // namespace route_table_fixture
